import {z} from "zod";import {currentProfile} from "@/lib/auth";import {createClient} from "@/lib/supabase/server";import {createAdminClient} from "@/lib/supabase/admin";import {apiError,apiSuccess,publicError} from "@/lib/api-response";
const base=z.object({kind:z.enum(["employee","booth","shift","stock_item","schedule","update_employee","update_booth","update_stock_item","reopen_stock"])}).passthrough();
export async function POST(request:Request){let createdUserId:string|undefined;try{const actor=await currentProfile();if(!actor||actor.role!=="admin"||!actor.is_active)return apiError("FORBIDDEN","Akses admin diperlukan.",403);const input=base.parse(await request.json());const supabase=await createClient();const admin=createAdminClient();
  if(input.kind==="employee"){const value=z.object({email:z.email(),full_name:z.string().min(2).max(100),password:z.string().min(8),booth_id:z.uuid().optional()}).parse(input);const {data,error}=await admin.auth.admin.createUser({email:value.email,password:value.password,email_confirm:true});if(error)throw error;createdUserId=data.user.id;const {error:profileError}=await admin.from("profiles").insert({id:createdUserId,email:value.email,full_name:value.full_name,role:"employee",employment_start_date:new Date().toISOString().slice(0,10)});if(profileError)throw profileError;if(value.booth_id){const {error:assignmentError}=await admin.from("employee_booth_assignments").insert({employee_id:createdUserId,booth_id:value.booth_id});if(assignmentError)throw assignmentError;}}
  else if(input.kind==="booth"){const value=z.object({name:z.string().min(2),address:z.string().max(300),latitude:z.coerce.number().min(-90).max(90),longitude:z.coerce.number().min(-180).max(180),radius:z.coerce.number().int().min(10).max(5000)}).parse(input);const {error}=await supabase.from("booths").insert({name:value.name,address:value.address,latitude:value.latitude,longitude:value.longitude,attendance_radius_m:value.radius});if(error)throw error;}
  else if(input.kind==="shift"){const value=z.object({booth_id:z.uuid(),name:z.string().min(2),start_time:z.string(),end_time:z.string(),tolerance:z.coerce.number().int().min(0).max(180)}).parse(input);const {error}=await supabase.from("shifts").insert({booth_id:value.booth_id,name:value.name,start_time:value.start_time,end_time:value.end_time,late_tolerance_minutes:value.tolerance});if(error)throw error;}
  else if(input.kind==="stock_item"){const value=z.object({name:z.string().min(2),unit:z.string().min(1),minimum:z.coerce.number().nonnegative()}).parse(input);const {data,error}=await supabase.from("stock_items").insert({name:value.name,unit:value.unit,default_minimum:value.minimum}).select("id").single();if(error)throw error;const {data:booths}=await supabase.from("booths").select("id").eq("is_active",true);if(booths?.length){const {error:linkError}=await supabase.from("booth_stock_items").insert(booths.map(booth=>({booth_id:booth.id,stock_item_id:data.id,minimum_stock:value.minimum})));if(linkError){await supabase.from("stock_items").delete().eq("id",data.id);throw linkError;}}}
  else if(input.kind==="schedule"){const value=z.object({employee_id:z.uuid(),booth_id:z.uuid(),shift_id:z.uuid(),work_date:z.iso.date()}).parse(input);const {error}=await supabase.from("employee_schedules").upsert(value,{onConflict:"employee_id,work_date"});if(error)throw error;}
  else if(input.kind==="update_employee"){const value=z.object({id:z.uuid(),full_name:z.string().min(2).max(100),phone:z.string().max(30),is_active:z.enum(["true","false"]).transform(v=>v==="true")}).parse(input);const {error}=await admin.from("profiles").update({full_name:value.full_name,phone:value.phone||null,is_active:value.is_active}).eq("id",value.id).eq("role","employee");if(error)throw error;}
  else if(input.kind==="update_booth"){const value=z.object({id:z.uuid(),name:z.string().min(2),address:z.string().max(300),latitude:z.coerce.number().min(-90).max(90),longitude:z.coerce.number().min(-180).max(180),radius:z.coerce.number().int().min(10).max(5000)}).parse(input);const {error}=await supabase.from("booths").update({name:value.name,address:value.address,latitude:value.latitude,longitude:value.longitude,attendance_radius_m:value.radius}).eq("id",value.id);if(error)throw error;}
  else if(input.kind==="update_stock_item"){const value=z.object({id:z.uuid(),name:z.string().min(2),unit:z.string().min(1),minimum:z.coerce.number().nonnegative()}).parse(input);const {error}=await supabase.from("stock_items").update({name:value.name,unit:value.unit,default_minimum:value.minimum}).eq("id",value.id);if(error)throw error;const {error:linkError}=await supabase.from("booth_stock_items").update({minimum_stock:value.minimum}).eq("stock_item_id",value.id);if(linkError)throw linkError;}
  else{const value=z.object({id:z.uuid()}).parse(input);const {data:photos,error:photoReadError}=await admin.from("stock_check_photos").select("original_path,watermarked_path").eq("stock_check_id",value.id);if(photoReadError)throw photoReadError;const {error:photosError}=await admin.from("stock_check_photos").delete().eq("stock_check_id",value.id);if(photosError)throw photosError;const {error:detailsError}=await admin.from("stock_check_details").delete().eq("stock_check_id",value.id);if(detailsError)throw detailsError;const {error:checkError}=await admin.from("stock_checks").delete().eq("id",value.id);if(checkError)throw checkError;await admin.from("audit_logs").insert({actor_id:actor.id,action:"reopen_stock_check",entity_type:"stock_check",entity_id:value.id,metadata:{requested_by:actor.id}});for(const photo of photos||[]){await admin.storage.from("stock-originals").remove([photo.original_path]);await admin.storage.from("stock-watermarked").remove([photo.watermarked_path]);}}
  return apiSuccess({saved:true});
}catch(error){if(createdUserId)await createAdminClient().auth.admin.deleteUser(createdUserId).catch(()=>undefined);console.error("ADMIN_MASTER_SAVE_FAILED",{kind:"master",error:error instanceof Error?error.message:String(error)});const safe=publicError(error,"Data belum berhasil disimpan.");return apiError(safe.code,safe.message,safe.status)}}
