export type UserRole = "admin" | "employee";
export type LocationInput = { latitude: number | null; longitude: number | null; accuracy: number | null };
export type AttendanceStatus = "on_time"|"late"|"outside_radius"|"location_unavailable"|"incomplete"|"pending_review"|"verified"|"rejected";
export function haversineMeters(a:{latitude:number;longitude:number},b:{latitude:number;longitude:number}) { const R=6_371_000; const rad=(n:number)=>n*Math.PI/180; const dLat=rad(b.latitude-a.latitude),dLon=rad(b.longitude-a.longitude); const x=Math.sin(dLat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dLon/2)**2; return 2*R*Math.asin(Math.sqrt(x)); }
export function lateMinutes(serverTime:Date, date:string, shiftStart:string, toleranceMinutes:number, timezone="Asia/Jakarta") { const zoned=new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(serverTime).reduce<Record<string,string>>((a,p)=>(a[p.type]=p.value,a),{}); if(`${zoned.year}-${zoned.month}-${zoned.day}`!==date)return 0; const [h,m]=shiftStart.split(":").map(Number); return Math.max(0,(Number(zoned.hour)*60+Number(zoned.minute))-(h*60+m)-toleranceMinutes); }
export function validateCheckout(checkIn:string,checkOut:string){if(new Date(checkOut)<=new Date(checkIn))throw new Error("Waktu pulang harus setelah waktu masuk");return true;}
export function storageName(userId:string,recordId:string,kind:string,extension="webp"){if(!/^[0-9a-f-]{36}$/i.test(userId)||!/^[0-9a-f-]{36}$/i.test(recordId))throw new Error("ID tidak valid");return `${userId}/${recordId}/${kind}-${crypto.randomUUID()}.${extension}`;}
export function safeCsvCell(value:unknown){const raw=String(value??"");const protectedValue=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return `"${protectedValue.replaceAll('"','""')}"`;}
export function toCsv(headers:string[],rows:unknown[][]){return "\uFEFF"+[headers,...rows].map(row=>row.map(safeCsvCell).join(",")).join("\r\n");}
