import Link from "next/link";
import {requireRole} from "@/lib/auth";
import {formatWib} from "@/lib/format";
import {getActiveBooth,getEmployeeTodayState,greetingWib} from "@/lib/operations";

export default async function EmployeeHome(){
  const profile=await requireRole("employee");const [booth,{attendance,stock}]=await Promise.all([getActiveBooth(),getEmployeeTodayState(profile.id)]);
  const firstName=profile.full_name.split(" ")[0];
  const primary=!attendance?{href:"/employee/attendance",label:"Presensi Masuk",icon:"📸"}:!stock?{href:"/employee/stock-check",label:"Cek Stok Sekarang",icon:"📦"}:!attendance.check_out_at?{href:"/employee/attendance",label:"Presensi Pulang",icon:"👋"}:null;
  return <div className="mobile-page"><section className="welcome"><div><p>{greetingWib()},</p><h1>{firstName}</h1><span>{new Intl.DateTimeFormat("id-ID",{timeZone:"Asia/Jakarta",weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date())}</span></div><div className="avatar">{profile.full_name.split(" ").map(word=>word[0]).join("").slice(0,2)}</div></section><div className="booth-chip"><span>📍</span>{booth?.name||"Booth belum dikonfigurasi"}</div><section className="activity-card"><div className="section-heading"><div><span className="eyebrow">Aktivitas Hari Ini</span><h2>Progres kerja</h2></div>{attendance?.check_out_at&&<span className="status status-good">Selesai</span>}</div><div className="timeline"><div className={attendance?"done":"current"}><span>{attendance?"✓":"1"}</span><div><strong>Presensi masuk</strong><small>{attendance?formatWib(attendance.check_in_at,true):"Belum dilakukan"}</small></div></div><div className={stock?"done":attendance?"current":""}><span>{stock?"✓":"2"}</span><div><strong>Cek stok</strong><small>{stock?formatWib(stock.checked_at,true):"Belum dilakukan"}</small></div></div><div className={attendance?.check_out_at?"done":stock?"current":""}><span>{attendance?.check_out_at?"✓":"3"}</span><div><strong>Presensi pulang</strong><small>{attendance?.check_out_at?formatWib(attendance.check_out_at,true):"Belum dilakukan"}</small></div></div></div></section>{primary?<section className="primary-action"><p>Langkah berikutnya</p><Link className="btn btn-primary btn-block btn-large" href={primary.href}><span>{primary.icon}</span>{primary.label}</Link>{attendance&&<Link className="btn btn-secondary btn-block" href="/employee/attendance">Lihat Presensi</Link>}</section>:<div className="success-banner"><span>✓</span><div><strong>Aktivitas hari ini selesai</strong><p>Terima kasih, semua kegiatan sudah tercatat.</p></div></div>}<section className="quick-note"><span>💡</span><p><strong>Ingat</strong><br/>Gunakan foto yang jelas dan hitung stok sesuai kondisi nyata di booth.</p></section></div>;
}
