import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { processPhoto } from "@/lib/photo";
import { attendanceUploadSchema } from "@/lib/validation";

export const runtime="nodejs";
export async function POST(request:Request){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"Sesi berakhir"},{status:401});try{const fd=await request.formData();const nullable=(v:FormDataEntryValue|null)=>v==null||v===""?null:Number(v);const input=attendanceUploadSchema.parse({action:fd.get("action"),idempotencyKey:fd.get("idempotencyKey"),latitude:nullable(fd.get("latitude")),longitude:nullable(fd.get("longitude")),accuracy:nullable(fd.get("accuracy"))});const file=fd.get("photo");if(!(file instanceof File))throw new Error("Foto wajib diambil");
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta"}).format(new Date());const {data:schedule}=await supabase.from("employee_schedules").select("booth_id,shift_id,booths(name),shifts(name)").eq("employee_id",user.id).eq("work_date",today).maybeSingle();if(!schedule)throw new Error("Jadwal hari ini tidak ditemukan");const {data:profile}=await supabase.from("profiles").select("full_name").eq("id",user.id).single();
 const serverTime=new Date();const display=new Intl.DateTimeFormat("id-ID",{timeZone:"Asia/Jakarta",dateStyle:"short",timeStyle:"medium"}).format(serverTime);const booth=(schedule.booths as unknown as {name:string})?.name||"Booth";const activity=input.action==="check_in"?"Presensi Masuk":"Presensi Pulang";const coords=input.latitude===null?"Lokasi tidak tersedia":`${input.latitude.toFixed(6)}, ${input.longitude?.toFixed(6)}`;const image=await processPhoto(file,[profile?.full_name||"Pekerja",booth,activity,`${display} WIB`,coords]);
 const recordKey=crypto.randomUUID(),base=`${user.id}/${recordKey}/${input.action}-${crypto.randomUUID()}.webp`;const admin=createAdminClient();const uploaded:string[]=[];for(const [bucket,body] of [["attendance-originals",image.original],["attendance-watermarked",image.watermarked]] as const){const {error}=await admin.storage.from(bucket).upload(base,body,{contentType:"image/webp",upsert:false});if(error){for(const b of uploaded)await admin.storage.from(b).remove([base]);throw error}uploaded.push(bucket)}
 const fn=input.action==="check_in"?"record_check_in":"record_check_out";const params=input.action==="check_in"?{p_original_path:base,p_watermarked_path:base,p_hash:image.hash,p_lat:input.latitude,p_lon:input.longitude,p_accuracy:input.accuracy,p_device:(request.headers.get("user-agent")||"").slice(0,300),p_idempotency:input.idempotencyKey}:{p_original_path:base,p_watermarked_path:base,p_hash:image.hash,p_lat:input.latitude,p_lon:input.longitude,p_accuracy:input.accuracy,p_idempotency:input.idempotencyKey};const {data,error}=await supabase.rpc(fn,params);if(error){for(const b of uploaded)await admin.storage.from(b).remove([base]);throw new Error(error.message)}return NextResponse.json({data,warning:data?.status==="outside_radius"?"Presensi tersimpan dan ditandai di luar radius.":data?.status==="location_unavailable"?"Presensi tersimpan tanpa lokasi dan perlu diperiksa.":null});
 }catch(error){const message=error instanceof Error?error.message:"Presensi gagal";return NextResponse.json({error:message},{status:400})}}
