"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {CameraCapture} from "@/components/camera-capture";
import {ErrorState} from "@/components/error-state";
import {parseApiResponse} from "@/lib/api";
type Item={id:string;name:string;unit:string;minimum:number};type Checklist={id:string;label:string};type Category="freezer"|"shelf"|"booth";
type Photo={category:Category;file:File|null};type Location={latitude:number|null;longitude:number|null;accuracy:number|null};
const photoInfo:{category:Category;label:string;guide:string}[]=[
  {category:"freezer",label:"Foto Freezer / Stok Ayam",guide:"Foto isi freezer atau persediaan ayam dengan jelas."},
  {category:"shelf",label:"Foto Rak Bahan & Kemasan",guide:"Pastikan bahan dan kemasan terlihat dalam satu foto."},
  {category:"booth",label:"Foto Area Booth",guide:"Ambil area kerja booth secara keseluruhan."},
];

export function StockCheckForm({boothName,date,items,checklists}:{boothName:string;date:string;items:Item[];checklists:Checklist[]}){
  const draftKey="rocky-stock-draft-v2";const [step,setStep]=useState(1);const [quantities,setQuantities]=useState<Record<string,number>>(()=>Object.fromEntries(items.map(item=>[item.id,0])));const [notes,setNotes]=useState<Record<string,string>>({});const [photos,setPhotos]=useState<Photo[]>(photoInfo.map(item=>({category:item.category,file:null})));const [conditions,setConditions]=useState<Record<string,"good"|"issue">>(()=>Object.fromEntries(checklists.map(item=>[item.id,"good"])));const [issueNote,setIssueNote]=useState("");const [busy,setBusy]=useState(false);const [stage,setStage]=useState("");const [error,setError]=useState("");const [success,setSuccess]=useState<{capturedAt:string}|null>(null);const idempotency=useRef(crypto.randomUUID());
  useEffect(()=>{const timer=window.setTimeout(()=>{try{const raw=localStorage.getItem(draftKey);if(raw){const draft=JSON.parse(raw);if(draft.quantities)setQuantities(current=>({...current,...draft.quantities}));if(draft.notes)setNotes(draft.notes);if(draft.conditions)setConditions(current=>({...current,...draft.conditions}));if(draft.issueNote)setIssueNote(draft.issueNote);}}catch{}},0);return()=>window.clearTimeout(timer)},[]);
  useEffect(()=>{localStorage.setItem(draftKey,JSON.stringify({quantities,notes,conditions,issueNote}));},[quantities,notes,conditions,issueNote]);
  const counts=useMemo(()=>items.reduce((result,item)=>{const value=quantities[item.id]||0;const status=value<=0?"empty":value<=item.minimum?"low":"safe";result[status]++;return result;},{safe:0,low:0,empty:0}),[items,quantities]);
  const completedPhotos=photos.filter(photo=>photo.file).length;const issues=Object.values(conditions).filter(value=>value==="issue").length;
  function setQuantity(id:string,value:number){setQuantities(current=>({...current,[id]:Math.max(0,Number.isFinite(value)?value:0)}));}
  function setPhoto(category:Category,file:File|null){setPhotos(current=>current.map(photo=>photo.category===category?{...photo,file}:photo));}
  async function submit(){
    if(completedPhotos!==3){setStep(3);setError("Lengkapi tiga foto bukti sebelum mengirim.");return;}
    if(busy)return;setBusy(true);setError("");setStage("Menyiapkan foto…");
    let location:Location={latitude:null,longitude:null,accuracy:null};
    try{location=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(position=>resolve({latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy}),reject,{enableHighAccuracy:true,timeout:12000,maximumAge:0}));}catch{}
    const payload={idempotencyKey:idempotency.current,location,note:issueNote,details:items.map(item=>({stockItemId:item.id,physical:quantities[item.id]||0,note:notes[item.id]||""})),checklist:conditions,photoCategories:photos.map(photo=>photo.category)};
    const body=new FormData();body.set("payload",JSON.stringify(payload));photos.forEach(photo=>{if(photo.file)body.append("photos",photo.file,`${photo.category}.jpg`);});
    try{setStage("Mengunggah 3 foto…");const response=await fetch("/api/stock-checks",{method:"POST",body});setStage("Menyimpan hasil stok…");const result=await parseApiResponse<{recordId:string;capturedAt:string}>(response);if(!result.success)throw new Error(result.error.message);setStage("Selesai");localStorage.removeItem(draftKey);setSuccess({capturedAt:result.data.capturedAt});}
    catch(value){console.error("STOCK_CHECK_SUBMIT_FAILED",value);setError(value instanceof Error?value.message:"Laporan belum berhasil dikirim. Periksa koneksi lalu coba lagi.");setStage("");}
    finally{setBusy(false);}
  }
  if(success)return <div className="success-panel"><div className="success-mark">✓</div><span className="eyebrow">Laporan tersimpan</span><h1>Cek stok hari ini selesai</h1><p>Seluruh jumlah, checklist, dan tiga foto sudah diterima server.</p><div className="summary-row"><span>Waktu server</span><strong>{new Intl.DateTimeFormat("id-ID",{timeZone:"Asia/Jakarta",hour:"2-digit",minute:"2-digit",day:"2-digit",month:"short",year:"numeric"}).format(new Date(success.capturedAt))} WIB</strong></div><div className="stock-summary"><span className="summary-safe">{counts.safe} aman</span><span className="summary-low">{counts.low} menipis</span><span className="summary-empty">{counts.empty} habis</span></div><a className="btn btn-primary btn-block" href="/employee">Kembali ke Beranda</a></div>;
  return <div className="stock-wizard"><div className="wizard-progress" aria-label={`Langkah ${step} dari 5`}>{[1,2,3,4,5].map(value=><span key={value} className={value<=step?"active":""}/>)}</div><div className="wizard-label">Langkah {step} dari 5</div>
    {step===1&&<section className="wizard-panel"><span className="eyebrow">Pengecekan Stok Hari Ini</span><h1>Periksa stok dengan tenang</h1><p className="lead">Hitung jumlah fisik yang benar-benar tersedia, ambil tiga foto bukti, lalu kirim setelah semuanya diperiksa.</p><div className="info-list"><div><span>📍</span><p><strong>{boothName}</strong><br/><small>{date}</small></p></div><div><span>1</span><p>Hitung stok fisik setiap item.</p></div><div><span>2</span><p>Ambil foto freezer, rak, dan area booth.</p></div><div><span>3</span><p>Periksa kondisi booth lalu kirim.</p></div></div><button className="btn btn-primary btn-block btn-large" onClick={()=>setStep(2)}>Mulai Cek Stok</button></section>}
    {step===2&&<section><div className="section-heading"><div><span className="eyebrow">Jumlah fisik</span><h1>Hitung stok yang tersedia</h1></div><span className="status">{items.length} item</span></div><p className="helper-text">Isi jumlah yang terlihat saat ini. Tekan “Habis” jika stok kosong.</p><div className="stock-card-list">{items.map(item=>{const quantity=quantities[item.id]||0;const status=quantity<=0?"Habis":quantity<=item.minimum?"Menipis":"Aman";return <article className="stock-item-card" key={item.id}><div className="stock-item-head"><div><h3>{item.name}</h3><p>{item.unit} • minimum {item.minimum}</p></div><span className={`status ${status==="Aman"?"status-good":status==="Menipis"?"status-warn":"status-bad"}`}>{status}</span></div><div className="quantity-control"><button type="button" aria-label={`Kurangi ${item.name}`} onClick={()=>setQuantity(item.id,quantity-1)}>−</button><input aria-label={`Jumlah ${item.name}`} inputMode="decimal" type="number" min="0" step="0.01" value={quantity} onChange={event=>setQuantity(item.id,Number(event.target.value))}/><button type="button" aria-label={`Tambah ${item.name}`} onClick={()=>setQuantity(item.id,quantity+1)}>+</button></div><div className="stock-item-actions"><button type="button" className="text-button danger" onClick={()=>setQuantity(item.id,0)}>Habis</button><input aria-label={`Catatan ${item.name}`} placeholder="Catatan opsional" value={notes[item.id]||""} onChange={event=>setNotes(current=>({...current,[item.id]:event.target.value}))}/></div></article>})}</div><div className="wizard-actions"><button className="btn btn-secondary" onClick={()=>setStep(1)}>Kembali</button><button className="btn btn-primary" onClick={()=>setStep(3)}>Lanjut ke Foto</button></div></section>}
    {step===3&&<section><div className="section-heading"><div><span className="eyebrow">Bukti kondisi</span><h1>Ambil tiga foto stok</h1></div><span className={`status ${completedPhotos===3?"status-good":"status-warn"}`}>{completedPhotos}/3</span></div><p className="helper-text">Gunakan kamera belakang. Foto tetap berada di halaman jika pengiriman gagal.</p><div className="photo-stack">{photoInfo.map(info=><CameraCapture key={info.category} label={info.label} facing="environment" guide={info.guide} onPhoto={file=>setPhoto(info.category,file)}/>)}</div>{error&&<ErrorState message={error}/>}<div className="wizard-actions"><button className="btn btn-secondary" onClick={()=>setStep(2)}>Kembali</button><button className="btn btn-primary" disabled={completedPhotos!==3} onClick={()=>{setError("");setStep(4)}}>Lanjut ke Kondisi</button></div></section>}
    {step===4&&<section><span className="eyebrow">Kondisi booth</span><h1>Apakah semuanya aman?</h1><div className="condition-list">{checklists.map(item=><article className="condition-card" key={item.id}><strong>{item.label}</strong><div className="segmented"><button type="button" className={conditions[item.id]==="good"?"active good":""} onClick={()=>setConditions(current=>({...current,[item.id]:"good"}))}>Baik</button><button type="button" className={conditions[item.id]==="issue"?"active issue":""} onClick={()=>setConditions(current=>({...current,[item.id]:"issue"}))}>Ada kendala</button></div></article>)}</div>{issues>0&&<label className="field card"><span>Jelaskan kendala</span><textarea rows={4} maxLength={1000} value={issueNote} onChange={event=>setIssueNote(event.target.value)} placeholder="Contoh: api kompor kecil atau freezer kurang dingin"/></label>}<div className="wizard-actions"><button className="btn btn-secondary" onClick={()=>setStep(3)}>Kembali</button><button className="btn btn-primary" disabled={issues>0&&!issueNote.trim()} onClick={()=>setStep(5)}>Lihat Ringkasan</button></div></section>}
    {step===5&&<section><span className="eyebrow">Siap dikirim</span><h1>Periksa ringkasan</h1><div className="stock-summary large"><span className="summary-safe"><strong>{counts.safe}</strong>Aman</span><span className="summary-low"><strong>{counts.low}</strong>Menipis</span><span className="summary-empty"><strong>{counts.empty}</strong>Habis</span></div><div className="summary-card"><div><span>Foto bukti</span><strong>{completedPhotos} lengkap</strong></div><div><span>Kondisi booth</span><strong>{issues?`${issues} kendala`:"Semua baik"}</strong></div><div><span>Catatan</span><strong>{issueNote||"Tidak ada"}</strong></div></div>{stage&&<div className="progress-card" role="status"><span className="spinner"/><div><strong>{stage}</strong><small>Jangan tutup halaman.</small></div></div>}{error&&<ErrorState message={`${error} Foto dan isian masih tersimpan.`} onRetry={()=>void submit()}/>}<div className="wizard-actions"><button className="btn btn-secondary" disabled={busy} onClick={()=>setStep(4)}>Kembali</button><button className="btn btn-primary" disabled={busy} onClick={()=>void submit()}>{busy?stage:"Kirim Hasil Cek Stok"}</button></div></section>}
  </div>;
}
