import {notFound} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {formatWib} from "@/lib/format";
import {VerifyForm} from "@/components/verify-form";
import {AdminCreateForm} from "@/components/admin-create-form";

export default async function StockDetail({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const sb=await createClient();const {data:check}=await sb.from("stock_checks").select("*,profiles(full_name),booths(name),stock_check_details(*,stock_items(name,unit)),stock_check_photos(*)").eq("id",id).single();if(!check)notFound();const {data:checklistMaster}=await sb.from("booth_checklists").select("id,label").eq("booth_id",check.booth_id);const checklistLabels=new Map((checklistMaster||[]).map(item=>[item.id,item.label]));
  const photos=check.stock_check_photos as unknown as {id:string;category:string;watermarked_path:string;photo_hash:string;captured_at:string}[];
  const details=check.stock_check_details as unknown as {id:string;physical_qty:number;minimum_stock:number;status:string;worker_note:string|null;stock_items:{name:string;unit:string}}[];
  const checklist=(check.checklist||{}) as Record<string,"good"|"issue">;
  return <><h1>Detail cek stok</h1><div className="card"><h2>{(check.booths as unknown as {name:string}).name}</h2><p>{(check.profiles as unknown as {full_name:string}).full_name} · {formatWib(check.checked_at)}</p><p>Lokasi: {check.location_status} · {check.latitude??"—"}, {check.longitude??"—"} · akurasi {check.accuracy_m??"—"} m · jarak {check.distance_m??"—"} m</p><p>Catatan kendala: {check.worker_note||"Tidak ada"}</p></div>
    <h2>Foto bukti</h2><div className="grid-cards">{photos.map(photo=><div className="card" key={photo.id}><strong>{photo.category}</strong><img src={`/api/photos/stock-watermarked/${photo.watermarked_path}`} alt={photo.category} style={{width:"100%",borderRadius:10,marginTop:10}}/><small style={{overflowWrap:"anywhere"}}>SHA-256: {photo.photo_hash}</small></div>)}</div>
    <h2>Jumlah fisik</h2><div className="card table-wrap"><table className="table"><thead><tr><th>Item</th><th>Jumlah fisik</th><th>Minimum</th><th>Status</th><th>Catatan</th></tr></thead><tbody>{details.map(detail=><tr key={detail.id}><td>{detail.stock_items.name} ({detail.stock_items.unit})</td><td>{detail.physical_qty}</td><td>{detail.minimum_stock}</td><td>{detail.status}</td><td>{detail.worker_note||"—"}</td></tr>)}</tbody></table></div>
    <h2>Kondisi booth</h2><div className="card">{Object.keys(checklist).length?Object.entries(checklist).map(([checklistId,value])=><p key={checklistId}><span className={`status ${value==="good"?"status-good":"status-warn"}`}>{value==="good"?"Baik":"Ada kendala"}</span> {checklistLabels.get(checklistId)||"Pemeriksaan booth"}</p>):<p>Checklist tidak tersedia.</p>}</div><VerifyForm type="stock_check" id={id}/><AdminCreateForm kind="reopen_stock" confirmMessage="Buka ulang cek stok? Laporan dan foto lama akan dihapus agar pekerja dapat mengirim ulang hari ini." redirectTo="/admin/stock-checks" submitLabel="Minta Pengecekan Ulang"><input type="hidden" name="id" value={id}/><h2>Buka ulang laporan</h2><p>Gunakan hanya bila pekerja memang harus mengirim ulang. Data dan foto laporan ini akan dihapus, sedangkan aksinya tetap dicatat pada audit log.</p></AdminCreateForm></>;
}
